name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install the project
        run: uv sync

      - name: Run check style
        run: uv run make style

  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install the project
        run: uv sync

      - name: Run check types
        run: uv run make types

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    needs: [lint, types]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version to ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync

      - name: Run tests
        run: uv run make test
